name: angular_crush
description: Angular Crush
version: 0.0.1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.0
  angular_forms: ^4.0.0
  intl: ^0.17.0
  font_awesome: ^5.10.1
  rxdart: ^0.27.2
  dio: ^4.0.0
  stream_transform: ^2.0.0

dev_dependencies:
  angular_test: ^4.0.0
  build_runner: ^2.1.2
  build_web_compilers: ^3.2.1
  test: ^1.3.0
